version: '3'
services:
  mongo:
    image: mongo:3.6.18-xenial
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    network_mode: host
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"

  hotel:
    build: hotel/
    image: hotel
    container_name: hotel
    depends_on:
      - mongo
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"